name: todo_app
description: A professional modern task management app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  uuid: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  shared_preferences: 2.3.2

dependency_overrides:
  shared_preferences_foundation: 2.4.0
  purchases_flutter: ^8.6.0
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0052CC"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#0052CC"
  image: "assets/icon/app_icon.png"
  android: true
  ios: true
  android_12:
    color: "#0052CC"
    image: "assets/icon/app_icon.png"
